// let keywordValue = searchBox.value;
let searchBox = document.querySelector("#search-box");
let images = document.querySelectorAll(".container .image-container .image");

searchBox.oninput = () => {
  images.forEach((hide) => (hide.style.display = "none"));
  let value = searchBox.value.toLowerCase();
  if (value.length >= 1) {
    document.getElementById(
      "keyword"
    ).innerHTML = `No Matches Found. Change your keywords and try again.`;
  } else {
    document.getElementById("keyword").innerHTML = "";
  }
  images.forEach((filter) => {
    let title = filter.getAttribute("data-title");
    let dataValue = filter.getAttribute("data-value");
    let fullValue = title + " " + dataValue;
    if (value == title) {
      filter.style.display = "block";
      document.getElementById(
        "keyword"
      ).innerHTML = `Showing results for "${value}"`;
    } else if (searchBox.value == "") {
      filter.style.display = "block";
    } else if (searchBox.value == dataValue) {
      filter.style.display = "block";
      document.getElementById(
        "keyword"
      ).innerHTML = `Showing results for "${dataValue}"`;
    } else if (searchBox.value == fullValue) {
      filter.style.display = "block";
      document.getElementById(
        "keyword"
      ).innerHTML = `Showing results for "${fullValue}"`;
    }
    // } else if (
    //   searchBox.value == "" ||
    //   searchBox.value == dataValue ||
    //   searchBox.value == fullValue
    // ) {
    //   filter.style.display = "none";
    //   //   document.getElementById(
    //   //     "keyword"
    //   //   ).innerHTML = `No Matches Found. Change your keywords and try again.`;
    // }
  });
};

function generateRandomImage() {
  //declare an array to store the images
  var randomImage = new Array();
  //insert the URL of images in array
  randomImage[0] = "images/pizza1.jpg";
  randomImage[1] = "images/pizza2.jpg";
  randomImage[2] = "images/pizza3.jpg";
  randomImage[3] = "images/pizza4.jpg";
  randomImage[4] = "images/pizza5.jpg";
  randomImage[5] = "images/pizza6.jpg";
  randomImage[6] = "images/pizza7.jpg";
  randomImage[7] = "images/pizza8.jpg";
  randomImage[8] = "images/pizza9.jpeg";
  var randomTopic = new Array();
  //insert the names of images in array
  randomTopic[0] = "Devilled Chicken";
  randomTopic[1] = "Cheese Lovers";
  randomTopic[2] = "Tandoori Chicken";
  randomTopic[3] = "Sausage Delight";
  randomTopic[4] = "Fiery Chicken";
  randomTopic[5] = "Margherita";
  randomTopic[6] = "Tropical Hawaiian";
  randomTopic[7] = "Pepperoni Paradiso";
  randomTopic[8] = "Seafood Supremo";
  for (let i = 0; i < 1; i++) {
    //generate a number and provide to the image to generate randomly
    var number = Math.floor(Math.random() * randomImage.length);
    //print the images and h3, generated by a random number
  }
  var headText = randomTopic[number];
  document.getElementsByClassName(
    "image-container",
    "h3"
  )[0].innerHTML = `<div class="image-container">
  <div class="image" data-title="cute" data-value="animal">
    <img src="${randomImage[number]}" alt="" />
    <h3>${headText}</h3>
  </div>`;
}
